twig:
    file_name_pattern: '*.twig'
    globals:
        lospae_version: '%env(LOSPAE_VERSION)%'
    paths:
        '%kernel.project_dir%/public/assets': assets

when@test:
    twig:
        strict_variables: true
